"""General analysis plug-in."""

from .config import (  # noqa: F401
    ALLOWED_LADDERS,
    ALLOWED_TRACE_CHANNELS,
    ASSAY_CONFIG,
    ASSAY_DISPLAY_ORDER,
    ASSAY_REFERENCE_LABEL,
    ASSAY_REFERENCE_RANGES,
    DEFAULT_BP_MAX,
    DEFAULT_BP_MIN,
    GENERAL_ASSAY_NAME,
    LIZ_LADDER,
    NONSPECIFIC_PEAKS,
    ROX_LADDER,
)
