#!/usr/bin/env python3
"""scripts/train_clonality_interpretation_models.py

Plan 11 / Phase 3 / T-3.1 CLI driver.

Trains per-assay clonality interpretation models on a labelled
tracking workbook. Persists:
  - One joblib artifact per (assay, classifier_kind)
  - A metadata.json per (assay, classifier_kind)
  - A markdown per-assay report under <output-dir>/<date>/

CLI:
  python -m scripts.train_clonality_interpretation_models \
      --xls /path/to/Clonality_Tracking.xlsx \
      --output-dir /path/to/models \
      --min-samples 200 \
      --classifier-kind random_forest \
      [--assays FR1,TCRG-A]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


# Make sure imports work whether script is invoked directly OR via
# `python -m scripts.train_clonality_interpretation_models`.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd

from core.analyses.clonality.ml_data_contract import (
    CHEMIST_LABEL_COLUMN,
    load_tracking_run_table,
)
from core.analyses.clonality.ml_training import (
    ANNOTATION_CLASSES_ORDER,
    build_per_assay_datasets,
    fit_classifier,
    serialize_model,
)
from core.analyses.clonality.ml_validation import (
    assess_promotion_gate,
    grouped_oof_validate,
    metrics_as_dict,
    render_review_panel_html,
)
from config import APP_SETTINGS


# Signature columns.
DIR_COL = "DIT"
ASSAY_COL = "Assay"
LABEL_COL = "ClonalitySuggestion"
AUTO_CLASSIFIER_KINDS = ("random_forest", "extra_trees")


def _assay_key(value):
    return (
        str(value or "")
        .strip()
        .replace(" ", "")
        .replace("-", "")
        .replace("_", "")
        .upper()
    )


def _per_assay_threshold_default(assay):
    """Pull from APP_SETTINGS, fall back to 0.85 if not configured."""
    cfg = APP_SETTINGS.get("analyses", {}).get("clonality", {})
    inter = cfg.get("interpretation", {})
    if not isinstance(inter, dict):
        return 0.85
    tau = inter.get("thresholds", {})
    if not isinstance(tau, dict):
        return 0.85
    assay_key = _assay_key(assay)
    for configured_assay, value in tau.items():
        if configured_assay != "_default" and _assay_key(configured_assay) == assay_key:
            return float(value)
    return float(tau.get("_default", 0.85))


def _assemble_labelled_df(xlsx_path, *, source_label_col=CHEMIST_LABEL_COLUMN):
    """Read a tracking XLSX and return the labelled combined frame.

    Current ``Runs`` workbooks are preferred. Legacy ``Run`` and split
    ``Patient_Runs``/``Control_Runs`` layouts remain supported.

    Requires a separate chemist-reviewed label column. Rule-based
    ``ClonalitySuggestion`` values are retained only as comparison data.
    """
    combined = load_tracking_run_table(
        xlsx_path,
        include_controls=False,
    ).frame
    if combined.empty:
        raise ValueError(f"no combined rows found in {xlsx_path}")
    required = (
        (source_label_col, source_label_col),
        (DIR_COL, "DIT"),
        (ASSAY_COL, "Assay"),
    )
    for col, name in required:
        if col not in combined.columns:
            raise KeyError(
                f"workbook {xlsx_path} has no {name!r} column; "
                "label samples in the Clonality Labeling tab first."
            )
    if source_label_col != LABEL_COL:
        combined[LABEL_COL] = combined[source_label_col]
    return combined


def _render_per_assay_markdown(
    metrics,
    who_called,
    *,
    validation,
    promotion_gate,
    runtime_eligible,
    model_comparison,
):
    """Emit a single markdown file per assay."""
    out_lines = []
    out_lines.append("# Clonality ML - Per-Assay Report: `{}`".format(metrics.assay))
    out_lines.append("")
    out_lines.append("_Generated by `{}`._".format(who_called))
    out_lines.append("")
    out_lines.append("## Summary")
    out_lines.append("")
    out_lines.append("- Assay: `{}`".format(metrics.assay))
    out_lines.append("- Classifier kind: `{}`".format(metrics.classifier_kind))
    out_lines.append("- Grouped out-of-fold samples: **{}**".format(len(validation.predictions)))
    out_lines.append("- Unique DIT groups: **{}**".format(
        validation.split_manifest["unique_dit_groups"]
    ))
    out_lines.append("- Validation folds: **{}**".format(
        validation.split_manifest["effective_splits"]
    ))
    out_lines.append("- Macro F1: **{:.3f}**".format(metrics.macro_f1))
    out_lines.append("- Accuracy: {:.3f}".format(metrics.accuracy))
    out_lines.append("- Balanced accuracy: {:.3f}".format(metrics.balanced_accuracy))
    out_lines.append("- Monoklonal-class F1 (rare-class focus): **{:.3f}**".format(metrics.monoklonal_f1))
    out_lines.append("- Accepted coverage at tau: {:.3f}".format(metrics.accepted_coverage))
    out_lines.append("- Accepted accuracy at tau: **{:.3f}**".format(metrics.accepted_accuracy))
    out_lines.append("- Expected calibration error: {:.3f}".format(
        metrics.expected_calibration_error
    ))
    out_lines.append("- Mean confidence: {:.3f}".format(metrics.mean_confidence))
    out_lines.append("- Per-assay acceptance threshold tau: {}".format(metrics.accept_threshold_tau))
    out_lines.append(
        "- Artifact status: **{}**".format(
            "runtime eligible" if runtime_eligible else "candidate only"
        )
    )
    out_lines.append("")
    out_lines.append("## Model comparison")
    out_lines.append("")
    out_lines.append(
        "| Classifier | Selected | Gate | Macro F1 | Mono precision | "
        "Mono F1 | Accepted accuracy | Coverage | ECE |"
    )
    out_lines.append("|---|---|---|---:|---:|---:|---:|---:|---:|")
    for row in model_comparison:
        if row.get("status") != "complete":
            out_lines.append(
                "| {} | no | failed | - | - | - | - | - | - |".format(
                    row.get("classifier_kind", "")
                )
            )
            continue
        display = {
            **row,
            "selected": "yes" if row["selected"] else "no",
            "gate": "pass" if row["promotion_gate_passed"] else "block",
        }
        out_lines.append(
            "| {classifier_kind} | {selected} | {gate} | {macro_f1:.3f} | "
            "{monoklonal_precision:.3f} | {monoklonal_f1:.3f} | "
            "{accepted_accuracy:.3f} | {accepted_coverage:.3f} | "
            "{expected_calibration_error:.3f} |".format(**display)
        )
    out_lines.append("")
    out_lines.append("## Promotion gate")
    out_lines.append("")
    out_lines.append("- Configured metrics pass: **{}**".format(
        "yes" if promotion_gate.passed else "no"
    ))
    for name, value in promotion_gate.thresholds.items():
        out_lines.append("- `{}`: {}".format(name, value))
    if promotion_gate.reasons:
        for reason in promotion_gate.reasons:
            out_lines.append("- Blocked: {}".format(reason))
    if promotion_gate.passed and not runtime_eligible:
        out_lines.append(
            "- Metrics pass, but explicit `--promote-if-passes` approval was not supplied."
        )
    out_lines.append("")
    out_lines.append("## Fold stability")
    out_lines.append("")
    out_lines.append(
        "| Fold | Train rows | Test rows | Macro F1 | Mono F1 | "
        "Balanced accuracy | Accepted accuracy | Coverage | ECE |"
    )
    out_lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in validation.fold_metrics.to_dict(orient="records"):
        out_lines.append(
            "| {Fold} | {TrainRows} | {TestRows} | {MacroF1:.3f} | "
            "{MonoklonalF1:.3f} | {BalancedAccuracy:.3f} | "
            "{AcceptedAccuracy:.3f} | {AcceptedCoverage:.3f} | "
            "{ExpectedCalibrationError:.3f} |".format(**row)
        )
    out_lines.append("")
    out_lines.append("## Rare-class counts")
    out_lines.append("")
    out_lines.append("| Class | Row count |")
    out_lines.append("|---|---|")
    for cls in ANNOTATION_CLASSES_ORDER:
        if cls in metrics.rare_class_counts:
            out_lines.append("| {} | {} |".format(cls, metrics.rare_class_counts[cls]))
    out_lines.append("")

    out_lines.append("## Confusion matrix")
    out_lines.append("")
    out_lines.append("Rows = true, Columns = predicted.")
    out_lines.append("")
    out_lines.append("```")
    cm = metrics.confusion_matrix
    if cm:
        label_keys = [k for k in metrics.classification_report
                      if k not in ("accuracy", "macro avg", "weighted avg") and metrics.classification_report[k].get("support") is not None]
        label_keys.sort(key=lambda k: ANNOTATION_CLASSES_ORDER.index(k) if k in ANNOTATION_CLASSES_ORDER else len(ANNOTATION_CLASSES_ORDER))
        if label_keys:
            out_lines.append(" " * 14 + " ".join("{:>8}".format(c[:6]) for c in label_keys))
            for label in label_keys:
                row_idx = next((i for i, k in enumerate(label_keys) if k == label), None)
                if row_idx is None:
                    continue
                row = cm[row_idx] if row_idx < len(cm) else []
                out_lines.append("{:<14}".format(label[:12]) + " ".join("{:>8d}".format(v) for v in row))
        else:
            for row in cm:
                out_lines.append(" ".join("{:>6d}".format(v) for v in row))
    out_lines.append("```")
    out_lines.append("")

    out_lines.append("## Per-class metrics")
    out_lines.append("")
    for cls in ANNOTATION_CLASSES_ORDER:
        d = metrics.classification_report.get(cls)
        if not d:
            continue
        out_lines.append(
            "- **{}**: precision={:.3f}, recall={:.3f}, f1={:.3f}, support={}".format(
                cls,
                float(d.get("precision", 0.0)),
                float(d.get("recall", 0.0)),
                float(d.get("f1-score", 0.0)),
                int(d.get("support", 0)),
            )
        )
    out_lines.append("")
    out_lines.append("## Decision notes")
    out_lines.append("")
    out_lines.append("- Rule-based interpretation remains the report source of truth.")
    out_lines.append("- ML is a second opinion; disagreement, low confidence, and rare-label predictions route to review.")
    out_lines.append("- Candidate artifacts are ignored by runtime until explicitly promoted after passing configured gates.")
    out_lines.append("")
    return chr(10).join(out_lines)


def _assemble_labelled_df_with_labels_csv(
    xlsx_path,
    labels_csv_path,
    *,
    source_label_col=CHEMIST_LABEL_COLUMN,
):
    """Variant that joins labels from a separate CSV.

    The CSV must have Assay, a chemist label, and either IdentityKey
    (preferred) or DIT. IdentityKey avoids spreading one label across
    multiple same-assay injections.
    """
    combined = load_tracking_run_table(
        xlsx_path,
        include_controls=False,
    ).frame
    if combined.empty:
        raise ValueError("no combined rows found in {}".format(xlsx_path))
    labels = pd.read_csv(labels_csv_path)
    label_aliases = (
        (CHEMIST_LABEL_COLUMN, "label", "y")
        if source_label_col == CHEMIST_LABEL_COLUMN
        else (source_label_col,)
    )
    column_aliases = {
        ASSAY_COL: ("assay",),
        source_label_col: label_aliases,
    }
    for col, aliases in column_aliases.items():
        if col in labels.columns:
            continue
        for alias in aliases:
            if alias in labels.columns:
                labels = labels.rename(columns={alias: col})
                break
        else:
            raise KeyError(
                "labels csv at {} has no {!r} column (or its alias)".format(
                    labels_csv_path, col,
                )
            )
    if "identity_key" in labels.columns and "IdentityKey" not in labels.columns:
        labels = labels.rename(columns={"identity_key": "IdentityKey"})
    if DIR_COL not in labels.columns and "dit" in labels.columns:
        labels = labels.rename(columns={"dit": DIR_COL})

    if "IdentityKey" in labels.columns and "IdentityKey" in combined.columns:
        join_columns = ["IdentityKey", ASSAY_COL]
    elif DIR_COL in labels.columns:
        join_columns = [DIR_COL, ASSAY_COL]
    else:
        raise KeyError(
            "labels csv must contain IdentityKey (preferred) or DIT for a leakage-safe join"
        )
    duplicate_labels = labels.duplicated(subset=join_columns, keep=False)
    if duplicate_labels.any():
        raise ValueError(
            "{} labels CSV row(s) duplicate join key {}".format(
                int(duplicate_labels.sum()), ", ".join(join_columns)
            )
        )
    combined = combined.drop(columns=[source_label_col], errors="ignore")
    merged = combined.merge(
        labels[join_columns + [source_label_col]],
        on=join_columns,
        how="inner",
        validate="many_to_one",
    )
    if merged.empty:
        raise ValueError("overlap between tracking features and labels was empty")
    if source_label_col != LABEL_COL:
        merged[LABEL_COL] = merged[source_label_col]
    return merged


def _assemble_trace_feature_df(
    xlsx_path,
    features_csv_path,
    *,
    source_label_col=CHEMIST_LABEL_COLUMN,
):
    """Join an offline trace artifact to the workbook's latest labels."""
    features = pd.read_csv(features_csv_path)
    required_features = {"IdentityKey", DIR_COL, ASSAY_COL}
    missing_features = sorted(required_features - set(features.columns))
    if missing_features:
        raise KeyError(
            "trace feature CSV is missing: {}".format(", ".join(missing_features))
        )

    tracking = load_tracking_run_table(
        xlsx_path,
        include_controls=False,
    ).frame
    required_tracking = {"IdentityKey", DIR_COL, ASSAY_COL, source_label_col}
    missing_tracking = sorted(required_tracking - set(tracking.columns))
    if missing_tracking:
        raise KeyError(
            "tracking workbook is missing: {}".format(", ".join(missing_tracking))
        )

    features = features.copy()
    tracking = tracking.copy()
    features["_AssayKey"] = features[ASSAY_COL].map(_assay_key)
    tracking["_AssayKey"] = tracking[ASSAY_COL].map(_assay_key)
    join_columns = ["IdentityKey", "_AssayKey"]

    feature_duplicates = features.duplicated(subset=join_columns, keep=False)
    if feature_duplicates.any():
        raise ValueError(
            f"{int(feature_duplicates.sum())} trace feature row(s) duplicate IdentityKey+Assay"
        )
    tracking_duplicates = tracking.duplicated(subset=join_columns, keep=False)
    if tracking_duplicates.any():
        raise ValueError(
            f"{int(tracking_duplicates.sum())} workbook row(s) duplicate IdentityKey+Assay"
        )

    current_labels = tracking[
        join_columns + [DIR_COL, source_label_col]
    ].rename(
        columns={
            DIR_COL: "_CurrentDIT",
            source_label_col: "_CurrentChemistLabel",
        }
    )
    features = features.drop(
        columns=[source_label_col, LABEL_COL],
        errors="ignore",
    )
    merged = features.merge(
        current_labels,
        on=join_columns,
        how="left",
        validate="one_to_one",
        indicator=True,
    )
    unmatched = merged["_merge"].ne("both")
    if unmatched.any():
        raise ValueError(
            f"{int(unmatched.sum())} trace feature row(s) no longer match the tracking workbook"
        )
    merged[DIR_COL] = merged["_CurrentDIT"].fillna("").astype(str)
    merged[LABEL_COL] = merged["_CurrentChemistLabel"]
    return merged.drop(
        columns=["_AssayKey", "_CurrentDIT", "_CurrentChemistLabel", "_merge"]
    )


def _ensure_columns_renamed(combined):
    """Best-effort column-renaming so DIT/Assay/ClonalitySuggestion exist."""
    renames = {}
    for old, new in (
        ("dit", DIR_COL), ("assay", ASSAY_COL), ("y", LABEL_COL),
        ("ClassLabel", LABEL_COL), ("label", LABEL_COL), ("interpretation", LABEL_COL),
    ):
        if old in combined.columns and new not in combined.columns:
            renames[old] = new
    return combined.rename(columns=renames) if renames else combined


def _training_data_fingerprint(dataset) -> str:
    columns = [
        column
        for column in (
            "IdentityKey",
            "FsaContentHash",
            DIR_COL,
            ASSAY_COL,
            LABEL_COL,
        )
        if column in dataset.rows.columns
    ]
    if columns:
        frame = dataset.rows[columns].fillna("").astype(str).copy()
    else:
        frame = pd.DataFrame(
            {
                DIR_COL: dataset.dit.astype(str),
                ASSAY_COL: dataset.assay,
                LABEL_COL: dataset.y.astype(str),
            }
        )
    payload = frame.sort_values(list(frame.columns), kind="stable").to_csv(
        index=False,
        lineterminator="\n",
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _first_value(frame, column):
    if column not in frame.columns:
        return ""
    values = frame[column].fillna("").astype(str).str.strip()
    values = values.loc[values.ne("")]
    return values.iloc[0] if not values.empty else ""


def _safe_assay_name(value):
    cleaned = "".join(
        character if character.isalnum() or character in {"-", "_"} else "_"
        for character in str(value)
    )
    return cleaned or "unknown"


def _candidate_gate(validation, args):
    return assess_promotion_gate(
        validation,
        min_macro_f1=args.min_macro_f1,
        min_monoklonal_f1=args.min_monoklonal_f1,
        min_monoklonal_precision=args.min_monoklonal_precision,
        min_dit_groups=args.min_dit_groups,
        min_accepted_accuracy=args.min_accepted_accuracy,
        min_accepted_coverage=args.min_accepted_coverage,
        max_expected_calibration_error=args.max_calibration_error,
    )


def _candidate_record(kind, validation, gate):
    metrics = validation.aggregate_metrics
    return {
        "classifier_kind": kind,
        "status": "complete",
        "selected": False,
        "promotion_gate_passed": gate.passed,
        "promotion_gate_reasons": gate.reasons,
        "macro_f1": metrics.macro_f1,
        "monoklonal_f1": metrics.monoklonal_f1,
        "monoklonal_precision": float(
            metrics.classification_report.get("monoklonal", {}).get(
                "precision", 0.0
            )
        ),
        "balanced_accuracy": metrics.balanced_accuracy,
        "accepted_accuracy": metrics.accepted_accuracy,
        "accepted_coverage": metrics.accepted_coverage,
        "expected_calibration_error": metrics.expected_calibration_error,
    }


def _candidate_selection_key(record):
    return (
        bool(record["promotion_gate_passed"]),
        float(record["monoklonal_precision"]),
        float(record["macro_f1"]),
        float(record["monoklonal_f1"]),
        float(record["accepted_accuracy"]),
        -float(record["expected_calibration_error"]),
    )


def _parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="Train per-assay clonality interpretation models."
    )
    p.add_argument(
        "--xls",
        type=Path,
        required=True,
        help="Path to Clonality_Tracking.xlsx with chemist labels populated.",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path.cwd() / "ObsidianVault" / "Clonality_ML_Log" / "models",
        help="Output directory for joblib artifacts, metadata, and reports.",
    )
    p.add_argument(
        "--date",
        type=str,
        default=None,
        help="Stamp date for the report (default: today UTC).",
    )
    p.add_argument(
        "--min-samples",
        type=int,
        default=200,
        help="Per-assay minimum row count to train a model (default 200).",
    )
    p.add_argument(
        "--classifier-kind",
        choices=("auto", "random_forest", "extra_trees", "qda_calibrated"),
        default="auto",
        help=(
            "Classifier family. 'auto' compares RandomForest and ExtraTrees "
            "with identical grouped folds and writes a candidate only."
        ),
    )
    p.add_argument(
        "--assays",
        type=str,
        default=None,
        help="Comma-separated assay name filter (default: all available).",
    )
    p.add_argument(
        "--labels-csv",
        type=Path,
        default=None,
        help="Optional chemist-label CSV keyed by IdentityKey+Assay or DIT+Assay.",
    )
    p.add_argument(
        "--features-csv",
        type=Path,
        default=None,
        help=(
            "Trace feature artifact from scripts.build_clonality_ml_features. "
            "Labels are refreshed from the tracking workbook by IdentityKey+Assay."
        ),
    )
    p.add_argument(
        "--label-column",
        default=CHEMIST_LABEL_COLUMN,
        help=(
            "Chemist-reviewed label column. Defaults to "
            f"{CHEMIST_LABEL_COLUMN!r}; use ClonalitySuggestion only for "
            "explicitly reviewed legacy workbooks."
        ),
    )
    p.add_argument(
        "--test-size",
        type=float,
        default=0.20,
        help="Deprecated compatibility option; grouped OOF validation uses folds.",
    )
    p.add_argument(
        "--validation-folds",
        type=int,
        default=5,
        help="Patient-grouped out-of-fold validation folds (default 5).",
    )
    p.add_argument(
        "--random-state",
        type=int,
        default=12345,
        help="Random seed for group-split (default 12345).",
    )
    p.add_argument(
        "--accept-threshold-tau",
        type=float,
        default=None,
        help=(
            "Override per-assay acceptance threshold tau (0..1). If omitted, "
            "the value is read from APP_SETTINGS.analyses.clonality.interpretation.thresholds."
        ),
    )
    p.add_argument(
        "--promote-if-passes",
        action="store_true",
        help=(
            "Mark models runtime eligible only when every configured validation "
            "gate passes. Without this flag all outputs remain candidates."
        ),
    )
    p.add_argument(
        "--min-macro-f1",
        type=float,
        default=0.70,
        help="Promotion gate for grouped OOF macro F1 (default 0.70).",
    )
    p.add_argument(
        "--min-monoklonal-f1",
        type=float,
        default=0.70,
        help="Promotion gate for grouped OOF monoklonal F1 (default 0.70).",
    )
    p.add_argument(
        "--min-monoklonal-precision",
        type=float,
        default=0.90,
        help="Promotion gate for monoklonal precision (default 0.90).",
    )
    p.add_argument(
        "--min-dit-groups",
        type=int,
        default=50,
        help="Minimum unique DIT groups required for promotion (default 50).",
    )
    p.add_argument(
        "--min-accepted-accuracy",
        type=float,
        default=0.95,
        help="Minimum OOF accuracy among predictions at/above tau (default 0.95).",
    )
    p.add_argument(
        "--min-accepted-coverage",
        type=float,
        default=0.10,
        help="Minimum OOF fraction at/above tau (default 0.10).",
    )
    p.add_argument(
        "--max-calibration-error",
        type=float,
        default=0.10,
        help="Maximum expected calibration error (default 0.10).",
    )
    return p.parse_args(argv)


def main(argv=None):
    args = _parse_args(argv)
    if args.classifier_kind == "auto" and args.promote_if_passes:
        raise ValueError(
            "--classifier-kind auto is comparison-only; inspect its reports, "
            "then rerun the selected classifier in a fresh output directory "
            "with --promote-if-passes"
        )

    xlsx_path = Path(args.xls)
    if not xlsx_path.exists():
        raise FileNotFoundError(f"--xls {xlsx_path} not found")
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    existing_models = sorted(output_dir.glob("*/metadata.json"))
    if existing_models:
        raise FileExistsError(
            "--output-dir already contains model artifacts; use a fresh "
            f"directory: {output_dir}"
        )
    today = args.date if args.date else datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_dir = output_dir / "reports" / today
    report_dir.mkdir(parents=True, exist_ok=True)
    print("[train] loading tracking workbook: {}".format(xlsx_path))
    if args.features_csv and args.labels_csv:
        raise ValueError("--features-csv and --labels-csv cannot be used together")
    if args.features_csv:
        if not Path(args.features_csv).is_file():
            raise FileNotFoundError("--features-csv {} not found".format(args.features_csv))
        combined = _assemble_trace_feature_df(
            xlsx_path,
            Path(args.features_csv),
            source_label_col=args.label_column,
        )
    elif args.labels_csv:
        if not Path(args.labels_csv).exists():
            raise FileNotFoundError("--labels-csv {} not found".format(args.labels_csv))
        combined = _assemble_labelled_df_with_labels_csv(
            xlsx_path, Path(args.labels_csv),
            source_label_col=args.label_column,
        )
    else:
        combined = _assemble_labelled_df(
            xlsx_path,
            source_label_col=args.label_column,
        )
    combined = _ensure_columns_renamed(combined)
    print("[train] combined rows: {}".format(len(combined)))

    include_assays = None
    if args.assays:
        include_assays = [s.strip() for s in args.assays.split(",") if s.strip()]

    print("[train] building per-assay datasets (min_samples={})".format(args.min_samples))
    datasets = build_per_assay_datasets(
        combined,
        include_assays=include_assays,
        min_samples_per_assay=args.min_samples,
    )

    if not datasets:
        raise SystemExit(
            "No assays produced a model; raise --min-samples or check the workbook."
        )

    print("[train] found {} qualifying assay(s): {}".format(
        len(datasets), ", ".join(sorted(datasets.keys()))))

    summaries = []
    failed_assays = []
    promotion_failures = []
    # Optional CLI override of per-assay tau — defaults to settings lookup.
    override_tau = getattr(args, "accept_threshold_tau", None)
    for assay_name in sorted(datasets.keys()):
        ds = datasets[assay_name]
        tau = (
            float(override_tau)
            if override_tau is not None
            else _per_assay_threshold_default(assay_name)
        )
        print("[train] assay={}: n_samples={}, tau={}".format(
            assay_name, ds.n_samples, tau))
        candidate_kinds = (
            AUTO_CLASSIFIER_KINDS
            if args.classifier_kind == "auto"
            else (args.classifier_kind,)
        )
        validations = {}
        gates = {}
        model_comparison = []
        for classifier_kind in candidate_kinds:
            print(
                "[train] assay={} validating classifier={}".format(
                    assay_name,
                    classifier_kind,
                )
            )
            try:
                candidate_validation = grouped_oof_validate(
                    ds,
                    classifier_kind=classifier_kind,
                    n_splits=args.validation_folds,
                    random_state=args.random_state,
                    accept_threshold_tau=tau,
                )
                candidate_gate = _candidate_gate(candidate_validation, args)
                validations[classifier_kind] = candidate_validation
                gates[classifier_kind] = candidate_gate
                model_comparison.append(
                    _candidate_record(
                        classifier_kind,
                        candidate_validation,
                        candidate_gate,
                    )
                )
            except Exception as exc:
                model_comparison.append(
                    {
                        "classifier_kind": classifier_kind,
                        "status": "failed",
                        "selected": False,
                        "error": str(exc),
                    }
                )
                print(
                    "[train] assay={} classifier={} FAILED: {}".format(
                        assay_name,
                        classifier_kind,
                        exc,
                    )
                )
        successful_candidates = [
            record
            for record in model_comparison
            if record.get("status") == "complete"
        ]
        if not successful_candidates:
            failed_assays.append(
                {
                    "assay": assay_name,
                    "error": "all classifier candidates failed",
                    "model_comparison": model_comparison,
                }
            )
            continue
        selected_record = max(
            successful_candidates,
            key=_candidate_selection_key,
        )
        selected_record["selected"] = True
        selected_kind = str(selected_record["classifier_kind"])
        validation = validations[selected_kind]
        gate = gates[selected_kind]
        print(
            "[train] assay={} selected classifier={}".format(
                assay_name,
                selected_kind,
            )
        )
        try:
            runtime_eligible = bool(args.promote_if_passes and gate.passed)
            if args.promote_if_passes and not gate.passed:
                promotion_failures.append(assay_name)
            estimator = fit_classifier(
                ds.X,
                ds.y,
                kind=selected_kind,
                random_state=args.random_state,
            )
        except Exception as exc:
            print("[train] assay={} FAILED validation/training: {}".format(assay_name, exc))
            failed_assays.append({"assay": assay_name, "error": str(exc)})
            continue
        metrics = validation.aggregate_metrics
        validation_metadata = {
            "strategy": validation.split_manifest["strategy"],
            "group_column": validation.split_manifest["group_column"],
            "effective_splits": validation.split_manifest["effective_splits"],
            "random_state": validation.split_manifest["random_state"],
            "unique_dit_groups": validation.split_manifest["unique_dit_groups"],
            "every_row_oof_once": validation.split_manifest["every_row_oof_once"],
            "metrics": metrics_as_dict(metrics),
            "promotion_gate": {
                "passed": gate.passed,
                "reasons": gate.reasons,
                "thresholds": gate.thresholds,
            },
            "model_selection": {
                "requested_classifier_kind": args.classifier_kind,
                "selected_classifier_kind": selected_kind,
                "selection_order": [
                    "promotion_gate_passed",
                    "monoklonal_precision",
                    "macro_f1",
                    "monoklonal_f1",
                    "accepted_accuracy",
                    "lower_expected_calibration_error",
                ],
                "candidates": model_comparison,
            },
        }
        paths = serialize_model(
            estimator,
            label_order=list(ANNOTATION_CLASSES_ORDER),
            assay=assay_name,
            accept_threshold_tau=tau,
            classifier_kind=selected_kind,
            rare_class_counts=ds.rare_class_counts,
            trained_at_utc=today,
            output_dir=output_dir,
            feature_columns=list(ds.X.columns),
            schema_version="ml_training_pipeline_v2",
            extra_metadata={
                "deployment_status": (
                    "validated" if runtime_eligible else "candidate"
                ),
                "runtime_eligible": runtime_eligible,
                "training_rows": ds.n_samples,
                "training_dit_groups": int(ds.dit.nunique()),
                "training_data_fingerprint": _training_data_fingerprint(ds),
                "feature_dataset_version": _first_value(
                    ds.rows, "FeatureDatasetVersion"
                ),
                "trace_feature_schema_version": _first_value(
                    ds.rows, "TraceFeatureSchemaVersion"
                ),
                "cohort_feature_schema_version": _first_value(
                    ds.rows, "CohortFeatureSchemaVersion"
                ),
                "validation": validation_metadata,
            },
        )
        report_stem = _safe_assay_name(assay_name)
        report_path = report_dir / "report_{}.md".format(report_stem)
        report_path.write_text(
            _render_per_assay_markdown(
                metrics,
                who_called="train_clonality_interpretation_models",
                validation=validation,
                promotion_gate=gate,
                runtime_eligible=runtime_eligible,
                model_comparison=model_comparison,
            ),
            encoding="utf-8",
        )
        predictions_path = report_dir / "predictions_{}.csv".format(report_stem)
        review_path = report_dir / "review_cases_{}.csv".format(report_stem)
        review_html_path = report_dir / "review_panel_{}.html".format(report_stem)
        drift_path = report_dir / "drift_{}.csv".format(report_stem)
        split_path = report_dir / "splits_{}.json".format(report_stem)
        metrics_path = report_dir / "metrics_{}.json".format(report_stem)
        comparison_path = report_dir / "model_comparison_{}.json".format(
            report_stem
        )
        comparison_csv_path = report_dir / "model_comparison_{}.csv".format(
            report_stem
        )
        validation.predictions.to_csv(predictions_path, index=False)
        validation.review_cases.to_csv(review_path, index=False)
        validation.drift_summary.to_csv(drift_path, index=False)
        review_html_path.write_text(
            render_review_panel_html(validation, promotion_gate=gate),
            encoding="utf-8",
        )
        split_path.write_text(
            json.dumps(validation.split_manifest, indent=2, sort_keys=True),
            encoding="utf-8",
        )
        metrics_path.write_text(
            json.dumps(metrics_as_dict(metrics), indent=2, sort_keys=True),
            encoding="utf-8",
        )
        comparison_path.write_text(
            json.dumps(model_comparison, indent=2, sort_keys=True),
            encoding="utf-8",
        )
        pd.DataFrame(model_comparison).to_csv(comparison_csv_path, index=False)
        summaries.append({
            "assay": assay_name,
            "training_samples": metrics.training_samples,
            "monoklonal_f1": metrics.monoklonal_f1,
            "macro_f1": metrics.macro_f1,
            "monoklonal_precision": float(
                metrics.classification_report.get("monoklonal", {}).get(
                    "precision", 0.0
                )
            ),
            "accepted_accuracy": metrics.accepted_accuracy,
            "accepted_coverage": metrics.accepted_coverage,
            "expected_calibration_error": metrics.expected_calibration_error,
            "requested_classifier_kind": args.classifier_kind,
            "selected_classifier_kind": selected_kind,
            "runtime_eligible": runtime_eligible,
            "deployment_status": "validated" if runtime_eligible else "candidate",
            "promotion_gate_passed": gate.passed,
            "promotion_gate_reasons": gate.reasons,
            "model_path": str(paths["joblib"]),
            "report_path": str(report_path),
            "predictions_path": str(predictions_path),
            "review_cases_path": str(review_path),
            "review_panel_path": str(review_html_path),
            "drift_path": str(drift_path),
            "splits_path": str(split_path),
            "model_comparison_path": str(comparison_path),
        })

    summary_path = output_dir / "reports" / today / "summary.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(
        json.dumps(
            {
                "date": today,
                "summaries": summaries,
                "failed_assays": failed_assays,
                "explicit_promotion_requested": bool(args.promote_if_passes),
                "promotion_failures": promotion_failures,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    print("[train] wrote models to: {}".format(output_dir))
    print("[train] wrote reports to: {}".format(report_dir))
    if not summaries:
        print("[train] FAILED: no assay model completed")
        return 1
    if promotion_failures:
        print(
            "[train] promotion blocked for: {}".format(
                ", ".join(promotion_failures)
            )
        )
        return 2
    print("[train] DONE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
