#!/usr/bin/env python3
"""scripts/train_clonality_interpretation_models.py

Plan 11 / Phase 3 / T-3.1 CLI driver.

Trains per-assay clonality interpretation models on a labelled
tracking workbook. Persists:
  - One joblib artifact per (assay, classifier_kind)
  - A metadata.json per (assay, classifier_kind)
  - A markdown per-assay report under <output-dir>/<date>/

CLI:
  python -m scripts.train_clonality_interpretation_models \
      --xls /path/to/Clonality_Tracking.xlsx \
      --output-dir /path/to/models \
      --min-samples 200 \
      --classifier-kind random_forest \
      [--assays FR1,TCRG-A]
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


# Make sure imports work whether script is invoked directly OR via
# `python -m scripts.train_clonality_interpretation_models`.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd

from core.analyses.clonality.ml_data_contract import (
    CHEMIST_LABEL_COLUMN,
    load_tracking_run_table,
)
from core.analyses.clonality.ml_training import (
    ANNOTATION_CLASSES_ORDER,
    PerAssayDataset,
    build_per_assay_datasets,
    fit_classifier,
    group_shuffle_split_by_dit,
    per_assay_metrics,
    serialize_model,
)
from config import APP_SETTINGS


# Signature columns.
DIR_COL = "DIT"
ASSAY_COL = "Assay"
LABEL_COL = "ClonalitySuggestion"


def _per_assay_threshold_default(assay):
    """Pull from APP_SETTINGS, fall back to 0.85 if not configured."""
    cfg = APP_SETTINGS.get("analyses", {}).get("clonality", {})
    inter = cfg.get("interpretation", {})
    if not isinstance(inter, dict):
        return 0.85
    tau = inter.get("thresholds", {})
    if not isinstance(tau, dict):
        return 0.85
    return float(tau.get(assay, tau.get("_default", 0.85)))


def _assemble_labelled_df(xlsx_path, *, source_label_col=CHEMIST_LABEL_COLUMN):
    """Read a tracking XLSX and return the labelled combined frame.

    Current ``Runs`` workbooks are preferred. Legacy ``Run`` and split
    ``Patient_Runs``/``Control_Runs`` layouts remain supported.

    Requires a separate chemist-reviewed label column. Rule-based
    ``ClonalitySuggestion`` values are retained only as comparison data.
    """
    combined = load_tracking_run_table(
        xlsx_path,
        include_controls=False,
    ).frame
    if combined.empty:
        raise ValueError(f"no combined rows found in {xlsx_path}")
    required = (
        (source_label_col, source_label_col),
        (DIR_COL, "DIT"),
        (ASSAY_COL, "Assay"),
    )
    for col, name in required:
        if col not in combined.columns:
            raise KeyError(
                f"workbook {xlsx_path} has no {name!r} column; "
                "label samples in the Clonality Labeling tab first."
            )
    if source_label_col != LABEL_COL:
        combined[LABEL_COL] = combined[source_label_col]
    return combined


def _train_one_assay(
    ds,
    classifier_kind,
    test_size,
    random_state,
    accept_threshold_tau,
):
    """Train a per-assay classifier on the dataset's DIT-split fold.

    Returns (fitted_estimator, holdout_metrics).
    """
    train_idx, test_idx = group_shuffle_split_by_dit(
        ds.X,
        ds.y,
        ds.dit,
        test_size=test_size,
        random_state=random_state,
    )
    X_train = ds.X.iloc[train_idx]
    y_train = ds.y.iloc[train_idx]
    X_test = ds.X.iloc[test_idx]
    y_test = ds.y.iloc[test_idx]

    estimator = fit_classifier(
        X_train, y_train,
        kind=classifier_kind,
        random_state=random_state,
    )
    y_pred = estimator.predict(X_test)
    try:
        y_prob = estimator.predict_proba(X_test)
    except Exception:
        y_prob = None
    classes = list(getattr(estimator, "classes_", []))
    if not classes:
        try:
            classes = list(estimator.named_steps["qda"].classes_)
        except Exception:
            classes = sorted(set(y_pred.tolist()))

    metrics = per_assay_metrics(
        y_test,
        y_pred,
        y_prob,
        classes=classes,
        assay=ds.assay,
        training_samples=int(len(train_idx)),
        rare_class_counts=ds.rare_class_counts,
        accept_threshold_tau=accept_threshold_tau,
        classifier_kind=classifier_kind,
    )
    return estimator, metrics


def _render_per_assay_markdown(metrics, who_called):
    """Emit a single markdown file per assay."""
    out_lines = []
    out_lines.append("# Clonality ML - Per-Assay Report: `{}`".format(metrics.assay))
    out_lines.append("")
    out_lines.append("_Generated by `{}`._".format(who_called))
    out_lines.append("")
    out_lines.append("## Summary")
    out_lines.append("")
    out_lines.append("- Assay: `{}`".format(metrics.assay))
    out_lines.append("- Classifier kind: `{}`".format(metrics.classifier_kind))
    out_lines.append("- Training samples: **{}**".format(metrics.training_samples))
    out_lines.append("- Macro F1: **{:.3f}**".format(metrics.macro_f1))
    out_lines.append("- Accuracy: {:.3f}".format(metrics.accuracy))
    out_lines.append("- Balanced accuracy: {:.3f}".format(metrics.balanced_accuracy))
    out_lines.append("- Monoklonal-class F1 (rare-class focus): **{:.3f}**".format(metrics.monoklonal_f1))
    out_lines.append("- Per-assay acceptance threshold tau: {}".format(metrics.accept_threshold_tau))
    out_lines.append("")
    out_lines.append("## Rare-class counts")
    out_lines.append("")
    out_lines.append("| Class | Row count |")
    out_lines.append("|---|---|")
    for cls in ANNOTATION_CLASSES_ORDER:
        if cls in metrics.rare_class_counts:
            out_lines.append("| {} | {} |".format(cls, metrics.rare_class_counts[cls]))
    out_lines.append("")

    out_lines.append("## Confusion matrix")
    out_lines.append("")
    out_lines.append("Rows = predicted, Columns = true.")
    out_lines.append("")
    out_lines.append("```")
    cm = metrics.confusion_matrix
    if cm:
        label_keys = [k for k in metrics.classification_report
                      if k not in ("accuracy", "macro avg", "weighted avg") and metrics.classification_report[k].get("support") is not None]
        label_keys.sort(key=lambda k: ANNOTATION_CLASSES_ORDER.index(k) if k in ANNOTATION_CLASSES_ORDER else len(ANNOTATION_CLASSES_ORDER))
        if label_keys:
            out_lines.append(" " * 14 + " ".join("{:>8}".format(c[:6]) for c in label_keys))
            for label in label_keys:
                row_idx = next((i for i, k in enumerate(label_keys) if k == label), None)
                if row_idx is None:
                    continue
                row = cm[row_idx] if row_idx < len(cm) else []
                out_lines.append("{:<14}".format(label[:12]) + " ".join("{:>8d}".format(v) for v in row))
        else:
            for row in cm:
                out_lines.append(" ".join("{:>6d}".format(v) for v in row))
    out_lines.append("```")
    out_lines.append("")

    out_lines.append("## Per-class metrics")
    out_lines.append("")
    for cls in ANNOTATION_CLASSES_ORDER:
        d = metrics.classification_report.get(cls)
        if not d:
            continue
        out_lines.append(
            "- **{}**: precision={:.3f}, recall={:.3f}, f1={:.3f}, support={}".format(
                cls,
                float(d.get("precision", 0.0)),
                float(d.get("recall", 0.0)),
                float(d.get("f1-score", 0.0)),
                int(d.get("support", 0)),
            )
        )
    out_lines.append("")
    out_lines.append("## Decision notes")
    out_lines.append("")
    out_lines.append("- tau defines the calibration threshold above which the ML suggestion is auto-accepted. Today's values are Phase-3 first cuts; chemist will calibrate per assay.")
    out_lines.append("- If monoklonal-class F1 < 0.70, do not auto-apply; route to `usikker_review` instead.")
    out_lines.append("- Trigger xgboost promotion per `decisions/xgboost_pending.md`: rare-class F1 < 0.85 across multiple chemist-validations.")
    out_lines.append("")
    return chr(10).join(out_lines)


def _assemble_labelled_df_with_labels_csv(
    xlsx_path,
    labels_csv_path,
    entry_metadata_path=None,
    *,
    source_label_col=CHEMIST_LABEL_COLUMN,
):
    """Variant that joins labels from a separate CSV.

    The CSV must have Assay, a chemist label, and either IdentityKey
    (preferred) or DIT. IdentityKey avoids spreading one label across
    multiple same-assay injections.
    """
    combined = load_tracking_run_table(
        xlsx_path,
        include_controls=False,
    ).frame
    if combined.empty:
        raise ValueError("no combined rows found in {}".format(xlsx_path))
    labels = pd.read_csv(labels_csv_path)
    label_aliases = (
        (CHEMIST_LABEL_COLUMN, "label", "y")
        if source_label_col == CHEMIST_LABEL_COLUMN
        else (source_label_col,)
    )
    column_aliases = {
        ASSAY_COL: ("assay",),
        source_label_col: label_aliases,
    }
    for col, aliases in column_aliases.items():
        if col in labels.columns:
            continue
        for alias in aliases:
            if alias in labels.columns:
                labels = labels.rename(columns={alias: col})
                break
        else:
            raise KeyError(
                "labels csv at {} has no {!r} column (or its alias)".format(
                    labels_csv_path, col,
                )
            )
    if "identity_key" in labels.columns and "IdentityKey" not in labels.columns:
        labels = labels.rename(columns={"identity_key": "IdentityKey"})
    if DIR_COL not in labels.columns and "dit" in labels.columns:
        labels = labels.rename(columns={"dit": DIR_COL})

    if "IdentityKey" in labels.columns and "IdentityKey" in combined.columns:
        join_columns = ["IdentityKey", ASSAY_COL]
    elif DIR_COL in labels.columns:
        join_columns = [DIR_COL, ASSAY_COL]
    else:
        raise KeyError(
            "labels csv must contain IdentityKey (preferred) or DIT for a leakage-safe join"
        )
    duplicate_labels = labels.duplicated(subset=join_columns, keep=False)
    if duplicate_labels.any():
        raise ValueError(
            "{} labels CSV row(s) duplicate join key {}".format(
                int(duplicate_labels.sum()), ", ".join(join_columns)
            )
        )
    combined = combined.drop(columns=[source_label_col], errors="ignore")
    merged = combined.merge(
        labels[join_columns + [source_label_col]],
        on=join_columns,
        how="inner",
        validate="many_to_one",
    )
    if merged.empty:
        raise ValueError("overlap between tracking features and labels was empty")
    if source_label_col != LABEL_COL:
        merged[LABEL_COL] = merged[source_label_col]
    return merged


def _ensure_columns_renamed(combined):
    """Best-effort column-renaming so DIT/Assay/ClonalitySuggestion exist."""
    renames = {}
    for old, new in (
        ("dit", DIR_COL), ("assay", ASSAY_COL), ("y", LABEL_COL),
        ("ClassLabel", LABEL_COL), ("label", LABEL_COL), ("interpretation", LABEL_COL),
    ):
        if old in combined.columns and new not in combined.columns:
            renames[old] = new
    return combined.rename(columns=renames) if renames else combined

def _parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="Train per-assay clonality interpretation models."
    )
    p.add_argument(
        "--xls",
        type=Path,
        required=True,
        help="Path to Clonality_Tracking.xlsx with chemist labels populated.",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path.cwd() / "ObsidianVault" / "Clonality_ML_Log" / "models",
        help="Output directory for joblib artifacts, metadata, and reports.",
    )
    p.add_argument(
        "--date",
        type=str,
        default=None,
        help="Stamp date for the report (default: today UTC).",
    )
    p.add_argument(
        "--min-samples",
        type=int,
        default=200,
        help="Per-assay minimum row count to train a model (default 200).",
    )
    p.add_argument(
        "--classifier-kind",
        choices=("random_forest", "qda_calibrated"),
        default="random_forest",
        help="Classifier family (default random_forest).",
    )
    p.add_argument(
        "--assays",
        type=str,
        default=None,
        help="Comma-separated assay name filter (default: all available).",
    )
    p.add_argument(
        "--labels-csv",
        type=Path,
        default=None,
        help="Optional chemist-label CSV keyed by IdentityKey+Assay or DIT+Assay.",
    )
    p.add_argument(
        "--label-column",
        default=CHEMIST_LABEL_COLUMN,
        help=(
            "Chemist-reviewed label column. Defaults to "
            f"{CHEMIST_LABEL_COLUMN!r}; use ClonalitySuggestion only for "
            "explicitly reviewed legacy workbooks."
        ),
    )
    p.add_argument(
        "--entry-metadata",
        type=Path,
        default=None,
        help="Optional JSON file keyed on identity_key with extra metadata per FSA file. Required when build_clonality_feature_tables cannot otherwise populate identity_key.",
    )
    p.add_argument(
        "--test-size",
        type=float,
        default=0.20,
        help="Holdout fraction (default 0.20).",
    )
    p.add_argument(
        "--random-state",
        type=int,
        default=12345,
        help="Random seed for group-split (default 12345).",
    )
    p.add_argument(
        "--accept-threshold-tau",
        type=float,
        default=None,
        help=(
            "Override per-assay acceptance threshold τ (0..1). If omitted, "
            "the value is read from APP_SETTINGS.analyses.clonality.interpretation.thresholds."
        ),
    )
    return p.parse_args(argv)


def main(argv=None):
    args = _parse_args(argv)

    xlsx_path = Path(args.xls)
    if not xlsx_path.exists():
        raise FileNotFoundError(f"--xls {xlsx_path} not found")
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    today = args.date if args.date else datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_dir = output_dir / "reports" / today
    report_dir.mkdir(parents=True, exist_ok=True)
    print("[train] loading tracking workbook: {}".format(xlsx_path))
    if args.labels_csv:
        if not Path(args.labels_csv).exists():
            raise FileNotFoundError("--labels-csv {} not found".format(args.labels_csv))
        combined = _assemble_labelled_df_with_labels_csv(
            xlsx_path, Path(args.labels_csv),
            entry_metadata_path=args.entry_metadata,
            source_label_col=args.label_column,
        )
    else:
        combined = _assemble_labelled_df(
            xlsx_path,
            source_label_col=args.label_column,
        )
    combined = _ensure_columns_renamed(combined)
    print("[train] combined rows: {}".format(len(combined)))

    include_assays = None
    if args.assays:
        include_assays = [s.strip() for s in args.assays.split(",") if s.strip()]

    print("[train] building per-assay datasets (min_samples={})".format(args.min_samples))
    datasets = build_per_assay_datasets(
        combined,
        include_assays=include_assays,
        min_samples_per_assay=args.min_samples,
    )

    if not datasets:
        raise SystemExit(
            "No assays produced a model; raise --min-samples or check the workbook."
        )

    print("[train] found {} qualifying assay(s): {}".format(
        len(datasets), ", ".join(sorted(datasets.keys()))))

    summaries = []
    # Optional CLI override of per-assay tau — defaults to settings lookup.
    override_tau = getattr(args, "accept_threshold_tau", None)
    for assay_name in sorted(datasets.keys()):
        ds = datasets[assay_name]
        tau = (
            float(override_tau)
            if override_tau is not None
            else _per_assay_threshold_default(assay_name)
        )
        print("[train] assay={}: n_samples={}, tau={}".format(
            assay_name, ds.n_samples, tau))
        try:
            estimator, metrics = _train_one_assay(
                ds,
                classifier_kind=args.classifier_kind,
                test_size=args.test_size,
                random_state=args.random_state,
                accept_threshold_tau=tau,
            )
        except Exception as exc:
            print("[train] assay={} FAILED to fit: {}".format(assay_name, exc))
            continue
        paths = serialize_model(
            estimator,
            label_order=list(ANNOTATION_CLASSES_ORDER),
            assay=assay_name,
            accept_threshold_tau=tau,
            classifier_kind=args.classifier_kind,
            rare_class_counts=ds.rare_class_counts,
            trained_at_utc=today,
            output_dir=output_dir,
            feature_columns=list(ds.X.columns),
        )
        report_path = report_dir / "report_{}.md".format(assay_name)
        report_path.write_text(
            _render_per_assay_markdown(metrics, who_called="train_clonality_interpretation_models"),
            encoding="utf-8",
        )
        summaries.append({
            "assay": assay_name,
            "training_samples": metrics.training_samples,
            "monoklonal_f1": metrics.monoklonal_f1,
            "macro_f1": metrics.macro_f1,
            "model_path": str(paths["joblib"]),
            "report_path": str(report_path),
        })

    summary_path = output_dir / "reports" / today / "summary.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps({"date": today, "summaries": summaries}, indent=2), encoding="utf-8")

    print("[train] wrote models to: {}".format(output_dir))
    print("[train] wrote reports to: {}".format(report_dir))
    print("[train] DONE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
